### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Andres8427** [Prior99/mumble-bot#4]
Hi,

I'm looking for how to record the conversations of Mumble server (murmur) and I run into its repository, I think it can be very helpful, however I can not get it to work, I'm following the steps you mention but it shows me this error:

![image](https://user-images.githubusercontent.com/33126305/54213982-6375a580-44b3-11e9-9003-017cfb2f5bff.png)

Can you please guide me in what I'm doing wrong ?. Thank you.

**Comment by Prior99** [comment]
Hi,

This project moved to gitlab quite a while ago and was rewriten in major parts. [Take a look at](https://gitlab.com/prior99/mumble-bot) the new project. It features better configurability, a CLI, better UI and more features.

**Comment by Andres8427** [comment]
Hello,

Thanks for the quick reply. It seems that the link that you send to me does not work and I do not find mumble-bot in the list of Gitlab projects, please confirm if it is a private repository or what is the updated link!

Thank you.

**Comment by Prior99** [comment]
You are right. I made it public. Sorry ^^'

**Comment by Andres8427** [comment]
Hello,

I'm glad that this project is more active, I hope to prove it, understand it and be able to contribute! I also see that you already consider Docker what I think is great!

However I'm giving a couple of heads trying to put it to work with my mumble server (murmur) to record the conversations.

You can guide me in the process !, you mention that it has a web interface but the Dockerfile does not expose any port, which port should I use, how do I integrate it with my mumble server? I do it through the file config.example.yml? I do not see that in the construction of the Docker it is used.

I'm sure these questions may sound stupid but the guide you can give me will be very helpful.

Thank you.

**Comment by Prior99** [comment]
I will see whether I can create a Dockerfile and a guide. The Dockerfile is currently only used for integration testing.

**Comment by Prior99** [comment]
In general, try cloning the repository on a Linux machine, run `make` and then `make run` or execute the server using node. It exposes a CLI. The directory `deploy/` as well as the `.gitlab-ci.yml` might also prove useful to you.

**Comment by Andres8427** [comment]
@Prior99 Thanks for the new indications, they are much clearer and I have managed to advance a little more, but it is generating an error when I run Make, I send you the full detail of the error.



root@ip-10-0-0-35:~/mumble-bot# make
yarn
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/11] ⠂ canvas
[2/11] ⠂ celt
[3/11] ⠂ jitterbuffer
[4/11] ⠂ ref
error /home/ubuntu/mumble-bot/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/ubuntu/mumble-bot/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/mumble-bot/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/mumble-bot/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory '/home/ubuntu/mumble-bot/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h:10:21: fatal error: jpeglib.h: No such file or directory
compilation terminated.
canvas.target.mk:133: recipe for target 'Release/obj.target/canvas/src/Canvas.o' failed
make[1]: Leaving directory '/home/ubuntu/mumble-bot/node_modules/canvas/build'
make[1]: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-1075-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/mumble-bot/node_modules/canvas




Makefile:21: recipe for target 'node_modules' failed
make: *** [node_modules] Error 1

**Comment by Prior99** [comment]
It reads it there, I think you need to install jpeglib. The Dockerfile
contains a sample command for installing all necessary dependencies.

**Comment by Prior99** [comment]
For example on Ubuntu you could go with:

```
sudo apt-get install libjpeg-dev
```

**Comment by Andres8427** [comment]
Hello, I'm already in the final steps! However, the config.yml file has been modified with the configuration, when trying to start the server. Show this error! I do not understand what I'm doing wrong!

![image](https://user-images.githubusercontent.com/33126305/54568644-06438d80-49a6-11e9-8179-1bc487145053.png)

**Comment by Prior99** [comment]
You need to specify the config file with `--config` or `-c` (You can also use `--help`). I forget to mention that in the README.

**Comment by Andres8427** [comment]
Hello,

Finally the bot is already shown on my mumble channel :) However it does not record the conversations :(

In the data folder nothing is written, I have given all the permissions to the folder and still nothing!

I also notice that in the postgres tables nothing is ever written, what should be written in these tables?

The frontend simply shows "Can not GET /", I have replaced in the file "dist / config.js" the URL where is the mumble-bot and the port, this is the same port that I configured in the confi.yml file, which should to show?

It seems that I am very close, and again I turn to your valuable help!

**Comment by Prior99** [comment]
I am happy to hear that you successfully started the bot. It will write audio files into the temp directory initially and only after saving them in the frontend they will be moved to the data directory. The database will be used for users, saved recordings, importes files, etc. 

The port and URL in the `config.js` should be publicly reachable and the port should be the same as in the `config.yml` file.

If it reads `Cannot GET /` I guess that you didn't make the frontend available.

To make this absolutely clear: The `node server serve` only serves the backend, a REST API for the bot. The frontend is built at compilation time (during `make`) and you need to copy it somewhere where your Apache2 oder nginx can serve it.

**Comment by Andres8427** [comment]
Hello again,

I already get the frontend to respond on apache, for test purposes I'm using port 80 by default, so in the config.yml configure port 80 in the varible "port" and in the config.js file configure as "baseUrl "the url publishes from the server where apache responds.

This shows the frontend, however when trying to create an initial user sample it is image error. Is something else missing? I still do not quite know why it still can not save the conversations, the management of users from frontend allows the mumble-bot to manage these recordings or something like that?

Thanks again for the help.

![image](https://user-images.githubusercontent.com/33126305/54618080-6aab2f00-4a30-11e9-8914-73c27e9d8d16.png)

**Comment by Prior99** [comment]
Looks like the frontend can't reach the backend and encounters a 404 error
page by apache. I'd recommend to take a look at the network inspector in
chrone.

**Comment by Andres8427** [comment]
Hi, I do not understand your answer very well: S

The DocumentRoot of my Apache is configured with the path of the folder "/dist", is this wrong?

How should I do it? the backend folder is the "/server"?

Thks

**Comment by Prior99** [comment]
Your directory is correct. However, the frontend needs to be served as
static files. It will then try to connect to the backend based on the URL
you have put into the config.js file. Make sure that either the backend is
reachable on that url directly (e.g. if you exposed it on port 12345, put
https://example.com:12345 into it) or ideally you would use a reverse proxy
setup.

To be clear: The frontend and the backend are basically two separate
applications talking to each other, both need to be publicly reachable. The
user's browser will connect to the frontend served feom dist/ and that will
then connect to the REST API that is served when you started the server
using node.

**Comment by Andres8427** [comment]
Hello,

I think that instead of advancing I'm going backwards ... I'll explain what I did:

Temporarily for tests (and to not configure even the reverse proxy) modify the Apache DocumentRoot to the mumble-bot path in my case "/home/ubuntu/mumble-bot/"

My mumble-bot service is running without problem and apache is listening to port 80 by default.

Modify the config.js file in the "dist" folder with the public URL of my apache server without port because it is using the default 80

However when I enter the http://IP_SERVER/dist my screen is blank, the console shows no errors and there is no error 404 of the dependency js and css of the index.html

What am I misunderstanding?

**Comment by Prior99** [comment]
It is pretty easy.

1. You start the backend with port 12345
2. You navigate to http://example.com/frontend
3. Your browser downloads the frontend, including a JS bundle and a config.js
4. The config.js contains http://example.com:12345
5. The frontend calls http://example.com:12345 to sign up the user, connect the websocket, etc. 

It is a very common, basic setup. A server serving the REST API and a SPA calling it. The only thing special here is that both reside within the same repository. 

You can take a look into the `deploy/` directory for sample configuration and instrumentation

**Comment by Andres8427** [comment]
Hello,

Yes, it really was a stupid error. I already managed to enter the backend, create the 2 users that are in my test channel, I could create a playlist and it works! I find it interesting but I am more interested in recording the conversations of the channel and this still does not work!

If I understand well with the settings link the users, however trying to do it shows me an error (see last image)

The user "robocop" does not appear in the link list but does not record the conversations either!

Am I making some other silly mistake?

![image](https://user-images.githubusercontent.com/33126305/54723085-6700d080-4b34-11e9-96f1-8091f78edfcc.png)

![image](https://user-images.githubusercontent.com/33126305/54723205-cbbc2b00-4b34-11e9-991f-973cf41e9fe7.png)

![image](https://user-images.githubusercontent.com/33126305/54722966-f6f24a80-4b33-11e9-92cf-cb61152ab9e5.png)

![image](https://user-images.githubusercontent.com/33126305/54723157-a7604e80-4b34-11e9-9414-bc3994d9ec48.png)

**Comment by Prior99** [comment]
You need to create a corresponding user in the bot's web interface and then
the user needs to Link to it in the settings.

E. g. he registers in the website, you unlock him, he goes to Settings on
top left, selects the mumble user, links, reconnects and your done.

The error is curious. Is the user registered on the mumble server? Or is he just a guest?

**Comment by Prior99** [comment]
When looking into the network tab of the Chrome dev tools and clicking on the 422 error and looking at the response, what does it read?

**Comment by Andres8427** [comment]
Hello,

The error it displays is: "{data: {body: {nested: {mumbleId: {errors: [" Not a valid integer. "]}}}}, Message:" Validation failed. "}
data: {body: {nested: {mumbleId: {errors: ["Not a valid integer."]}}}}
message: "Validation failed." "

And yes, users are registered. I send you the accesses to the test server I'm using if you want to see something

http://18.206.86.95
User: andres@yopmail.com
Password: XXXXX

Mumble Server: XXXX

**Comment by Prior99** [comment]
I will take a look at it, it's likely a bug. Hopefully I can find the time tomorrow in the evening.

Please note that this issue is public and you shared your IP and login information with the public.

**Comment by Prior99** [comment]
I had a busy weekend and sadly did not manage to take a look at this. I will also have a rather full week next week. I will keep you up to date.

**Comment by Prior99** [comment]
I took a look at this. The only problem is that the checkbox is not disabled. The user you are trying to link to is not registered on the mumble server.

One of the following might result in this:

* You might not have **registered** the user (Right click as super user or admin and click register)
* The user connected without a certificate

Trying to link such a user results in exactly this error. Registered users can be linked.
I pushed a commit to disable the checkbox if the user isn't linkable.

**Comment by Andres8427** [comment]
Hello, I continued analyzing the error and I made it work and now I have managed to save the conversations of my mumble channel.

However I must manually save to see the audio file and all the recordings are being registered by the same user mumble.

Is there any configuration for a self-save of the recordings? What should I do to distinguish which user the audio belongs to?

Thank you.

**Comment by Prior99** [comment]
There is no self-save feature. For distinguishing between the users you
have to create additional users in the mumble bot website. Every user
should simply sign up there, you unlock them, they link to the
corresponding user in the mumble server et voila they will show up as
different users.

Pullrequests for features like autosave are happily accepted.
